import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation strings
const translations = {
  en: {
    // Common
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    saving: 'Saving...',
    back: 'Back',
    
    // Navigation
    backToDashboard: 'Back to Dashboard',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    
    // Settings
    settingsTitle: 'Settings',
    languageRegion: 'Language & Region',
    interfaceLanguage: 'Interface Language',
    languageDescription: 'Select your preferred language',
    contentGenerationDefaults: 'Content Generation Defaults',
    defaultContentLength: 'Default Content Length',
    defaultTone: 'Default Tone',
    defaultTargetAge: 'Default Target Age',
    defaultLocation: 'Default Location',
    defaultPurpose: 'Default Purpose',
    defaultEmotion: 'Default Emotion',
    dataExport: 'Data Export',
    exportYourData: 'Export Your Data',
    exportDescription: 'Download all your content, settings, and account data',
    exportData: 'Export Data',
    exporting: 'Exporting...',
    usageBilling: 'Usage & Billing',
    currentPlan: 'Current Plan',
    upgradePlan: 'Upgrade Plan',
    
    // Profile
    profileSettings: 'Profile Settings',
    basicInformation: 'Basic Information',
    fullName: 'Full Name',
    username: 'Username',
    email: 'Email Address',
    changePhoto: 'Change Photo',
    
    // Dashboard
    welcomeBack: 'Welcome back!',
    createContent: 'Create Content',
    writeText: 'Write Text',
    uploadImage: 'Upload Image',
    recordVoice: 'Record Voice',
    generateImage: 'Generate Image',
    
    // Content Generation
    contentLength: 'Content Length',
    tone: 'Tone',
    targetAge: 'Target Age',
    location: 'Location',
    purpose: 'Purpose',
    emotion: 'Emotion',
    businessType: 'Business Type',
    
    // WriteTextModal
    createTextContent: 'Create Text Content',
    selectBusiness: 'Select Business',
    selectBusinessRequired: 'Please select a business',
    businessNameDropdown: 'Choose business to create content for...',
    addBusiness: 'Add',
    addNewBusiness: 'Add New Business',
    textPrompt: 'Text Prompt',
    textPromptPlaceholder: 'Describe what kind of text content you want to create...',
    textPromptRequired: 'Text prompt is required',
    textPromptMinLength: 'Prompt must be at least 10 characters',
    contentLengthRequired: 'Please select content length',
    short: 'Short',
    medium: 'Medium',
    long: 'Long',
    toneRequired: 'Please select a tone',
    professional: 'Professional',
    casual: 'Casual',
    friendly: 'Friendly',
    formal: 'Formal',
    humorous: 'Humorous',
    persuasive: 'Persuasive',
    targetAgeRequired: 'Please select target age',
    child: 'Child (5-12)',
    teen: 'Teen (13-17)',
    youngAdult: 'Young Adult (18-25)',
    adult: 'Adult (26-45)',
    senior: 'Senior (45+)',
    allAges: 'All Ages',
    locationRequired: 'Please select location',
    myanmar: 'Myanmar',
    global: 'Global',
    contentPurposeRequired: 'Please select content purpose',
    engagement: 'Engagement',
    conversion: 'Conversion', 
    lead: 'Lead',
    increaseFollower: 'Increase Follower',
    emotionRequired: 'Please select emotion',
    neutral: 'Neutral',
    happy: 'Happy',
    excited: 'Excited',
    calm: 'Calm',
    serious: 'Serious',
    inspiring: 'Inspiring',
    reference: 'Reference (Optional)',
    referencePlaceholder: 'Enter reference information (optional)...',
    generateContent: 'Generate Content',
    generating: 'Generating...',
    
    // RecordVoiceModal
    recordAudioContent: 'Record Audio Content',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    pauseRecording: 'Pause Recording',
    resumeRecording: 'Resume Recording',
    recordingTime: 'Recording Time',
    audioPreview: 'Audio Preview',
    reRecord: 'Re-record',
    uploadRecording: 'Upload Recording',
    voiceRecording: 'Voice Recording',
    recordingCompleted: 'Recording completed',
    recordAgain: 'Record Again',
    recordingIndicator: 'Recording...',
    recordAudioFirst: 'Please record audio before submitting',
    
    // UploadImageModal
    uploadImageContent: 'Upload Image Content',
    uploadImageFile: 'Upload Image File',
    chooseImageFile: 'Choose image file...',
    selectImageFile: 'Please select an image file',
    selectImage: 'Select Image',
    dragDropImage: 'Drag and drop an image here, or click to select',
    supportedFormats: 'Supported formats: JPG, PNG, GIF',
    maxFileSize: 'Maximum file size: 10MB',
    imagePreview: 'Image Preview',
    changeImage: 'Change Image',
    uploadImage: 'Upload Image',
    
    // ContentDetailModal
    copyContent: 'Copy Content',
    download: 'Download',
    recentContent: 'Recent Content',
    
    // Alert messages
    imageUploadSuccess: 'Image upload request submitted successfully!',
    formSubmissionFailed: 'Failed to submit form. Please try again.',
    
    // Dashboard
    whatCreateToday: 'What would you like to create today?',
    chooseOptions: 'Choose from the options below to start creating amazing content',
    writeTextDescription: 'Create articles, blogs, stories, and written content with our powerful text editor',
    uploadImageDescription: 'Upload image and create content',
    recordVoiceDescription: 'Record audio content, podcasts, voice-overs, and audio narratives',
    
    // Login Page
    welcomeBack: 'Welcome Back',
    signInToAccount: 'Sign in to your account',
    emailAddress: 'Email Address',
    enterEmail: 'Enter your email',
    emailRequired: 'Email is required',
    invalidEmail: 'Invalid email address',
    password: 'Password',
    enterPassword: 'Enter your password',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 6 characters',
    rememberMe: 'Remember me',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    dontHaveAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    loginFailed: 'Login failed. Please try again.',
    
    // Register Page
    createAccount: 'Create Account',
    joinUs: 'Join us and start creating amazing content',
    fullNameRequired: 'Full name is required',
    nameMinLength: 'Name must be at least 2 characters',
    enterFullName: 'Enter your full name',
    chooseUsername: 'Choose a username',
    usernameRequired: 'Username is required',
    usernameMinLength: 'Username must be at least 3 characters',
    usernamePattern: 'Username can only contain letters, numbers, and underscores',
    enterEmailAddress: 'Enter your email address',
    emailAddressRequired: 'Email address is required',
    createPassword: 'Create a password',
    passwordMinLength8: 'Password must be at least 8 characters',
    passwordPattern: 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    pleaseConfirmPassword: 'Please confirm your password',
    passwordsNotMatch: 'Passwords do not match',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    registrationFailed: 'Registration failed. Please try again.',
    
    // Profile Page
    backToDashboard: 'Back to Dashboard',
    profileSettings: 'Profile Settings',
    changePhoto: 'Change Photo',
    basicInformation: 'Basic Information',
    currentSubscription: 'Current Subscription',
    freePlan: 'Free Plan',
    proPlan: 'Pro Plan',
    premiumPlan: 'Premium Plan',
    active: 'Active',
    inactive: 'Inactive',
    nextBilling: 'Next billing',
    currentFeatures: 'Current Features',
    upgradeYourPlan: 'Upgrade Your Plan',
    mostPopular: 'Most Popular',
    currentPlan: 'Current Plan',
    upgradeToPro: 'Upgrade to Pro',
    upgradeToPremiun: 'Upgrade to Premium',
    allPlansInclude: 'All plans include a 14-day free trial. Cancel anytime.',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    currentPasswordRequired: 'Current password is required',
    newPassword: 'New Password',
    newPasswordRequired: 'New password is required',
    passwordMustContain: 'Password must contain uppercase, lowercase, and number',
    confirmNewPassword: 'Confirm New Password',
    pleaseConfirmNewPassword: 'Please confirm your new password',
    saveChanges: 'Save Changes',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileUpdateFailed: 'Failed to update profile. Please try again.',
    redirectingCheckout: 'Redirecting to {plan} plan checkout...',
    
    // Subscription Features
    feature1: '5 AI-generated contents per month',
    feature2: 'Basic templates',
    feature3: 'Standard support',
    feature4: 'Unlimited AI-generated content',
    feature5: 'Advanced templates',
    feature6: 'Priority support',
    feature7: 'Custom branding',
    feature8: 'Analytics dashboard',
    feature9: 'Everything in Pro',
    feature10: 'AI voice generation',
    feature11: 'Advanced image editing',
    feature12: 'Team collaboration',
    feature13: 'API access',
    feature14: 'White-label solutions',
    
    // Business Information Form
    businessInformation: 'Business Information',
    businessInformationDescription: 'Tell us about your business to help us create better content for you',
    businessName: 'Business Name',
    businessNamePlaceholder: 'e.g., "The Daily Grind Cafe"',
    businessNameRequired: 'Business name is required',
    businessNameMinLength: 'Business name must be at least 2 characters',
    businessNameMaxLength: 'Business name must not exceed 100 characters',
    coreOffering: 'Core Offering/Niche',
    coreOfferingPlaceholder: 'e.g., "Artisan coffee and homemade pastries"',
    coreOfferingRequired: 'Core offering is required',
    coreOfferingMinLength: 'Core offering must be at least 5 characters',
    coreOfferingMaxLength: 'Core offering must not exceed 200 characters',
    uniqueSellingProposition: 'Unique Selling Proposition (USP)',
    uniqueSellingPropositionPlaceholder: 'e.g., "We only use organic, ethically-sourced beans and donate 10% of profits to local shelters."',
    uniqueSellingPropositionRequired: 'Unique selling proposition is required',
    uniqueSellingPropositionMinLength: 'USP must be at least 10 characters',
    uniqueSellingPropositionMaxLength: 'USP must not exceed 500 characters',
    targetAudience: 'Target Audience',
    targetAudiencePlaceholder: 'e.g., "Remote workers and families in the downtown area."',
    targetAudienceRequired: 'Target audience is required',
    targetAudienceMinLength: 'Target audience must be at least 5 characters',
    targetAudienceMaxLength: 'Target audience must not exceed 200 characters',
    businessMission: 'What is your business\'s core mission or value?',
    businessMissionPlaceholder: 'e.g., "To provide sustainable, high-quality products while supporting local communities and environmental conservation."',
    businessMissionRequired: 'Business mission or value is required',
    businessMissionMinLength: 'Business mission must be at least 10 characters',
    businessMissionMaxLength: 'Business mission must not exceed 500 characters',
    saveBusinessInfo: 'Save Business Information',
    
    // Initial Business Setup
    setupFirstBusiness: 'Set Up Your First Business',
    businessSetupRequired: 'Please add at least one business before creating content',
    addFirstBusinessDescription: 'To get started with content creation, you need to add your business information first. This helps us create more relevant and targeted content for your brand.'
  },
  my: {
    // Common
    save: 'သိမ်းဆည်းမည်',
    cancel: 'ပယ်ဖျက်မည်',
    loading: 'တင်နေသည်...',
    saving: 'သိမ်းနေသည်...',
    back: 'နောက်သို့',
    
    // Navigation
    backToDashboard: 'မူလစာမျက်နှာသို့ပြန်သွားမည်',
    profile: 'ကိုယ်ရေးအကျဉ်း',
    settings: 'ဆက်တင်များ',
    logout: 'ထွက်မည်',
    
    // Settings
    settingsTitle: 'ဆက်တင်များ',
    languageRegion: 'ဘာသာစကားနှင့် ဒေသ',
    interfaceLanguage: 'အင်တာဖေ့စ် ဘာသာစကား',
    languageDescription: 'သင်နှစ်သက်သော ဘာသာစကားကို ရွေးချယ်ပါ',
    contentGenerationDefaults: 'အကြောင်းအရာ ဖန်တီးမှု ပုံမှန်များ',
    defaultContentLength: 'ပုံမှန် အကြောင်းအရာ အရှည်',
    defaultTone: 'ပုံမှန် လေသံ',
    defaultTargetAge: 'ရည်ရွယ်ထားသောအသက်အရွယ်',
    defaultLocation: 'ပုံမှန် တည်နေရာ',
    defaultPurpose: 'ပုံမှန် ရည်ရွယ်ချက်',
    defaultEmotion: 'ပုံမှန် စိတ်ခံစားမှု',
    dataExport: 'ဒေတာ ထုတ်ယူမှု',
    exportYourData: 'သင့်ဒေတာကို ထုတ်ယူပါ',
    exportDescription: 'သင့်အကြောင်းအရာ၊ ဆက်တင်များနှင့် အကောင့်ဒေတာ အားလုံးကို ဒေါင်းလုဒ်လုပ်ပါ',
    exportData: 'ဒေတာ ထုတ်ယူမည်',
    exporting: 'ထုတ်ယူနေသည်...',
    usageBilling: 'အသုံးပြုမှုနှင့် ငွေတောင်းခံမှု',
    currentPlan: 'လက်ရှိ အစီအစဉ်',
    upgradePlan: 'အစီအစဉ် အဆင့်မြှင့်တင်မည်',
    
    // Profile
    profileSettings: 'ကိုယ်ရေးအကျဉ်း ဆက်တင်များ',
    basicInformation: 'အခြေခံ အချက်အလက်များ',
    fullName: 'အမည်အပြည့်အစုံ',
    username: 'အသုံးပြုသူအမည်',
    email: 'အီးမေးလ်လိပ်စာ',
    changePhoto: 'ဓာတ်ပုံပြောင်းမည်',
    
    // Dashboard
    welcomeBack: 'ပြန်လည်ကြိုဆိုပါတယ်!',
    createContent: 'အကြောင်းအရာ ဖန်တီးမည်',
    writeText: 'စာသားရေးမည်',
    uploadImage: 'ပုံတင်မည်',
    recordVoice: 'အသံဖမ်းမည်',
    generateImage: 'ပုံဖန်တီးမည်',
    
    // Content Generation
    contentLength: 'အကြောင်းအရာ အရှည်',
    tone: 'အသံအနေ အသံထား',
    targetAge: 'ပစ်မှတ် အသက်အရွယ်',
    location: 'တည်နေရာ',
    purpose: 'ရည်ရွယ်ချက်',
    emotion: 'စိတ်ခံစားမှု',
    businessType: 'လုပ်ငန်းအမျိုးအစား',
    
    // WriteTextModal
    createTextContent: 'စာသား အကြောင်းအရာ ဖန်တီးမည်',
    selectBusiness: 'လုပ်ငန်း ရွေးချယ်မည်',
    selectBusinessRequired: 'ကျေးဇူးပြု၍ လုပ်ငန်းတစ်ခု ရွေးချယ်ပါ',
    businessNameDropdown: 'အကြောင်းအရာ ဖန်တီးမည့် လုပ်ငန်းကို ရွေးချယ်ပါ...',
    addBusiness: 'ထည့်မည်',
    addNewBusiness: 'လုပ်ငန်းအသစ် ထည့်မည်',
    textPrompt: 'စာသား တောင်းဆိုမှု',
    textPromptPlaceholder: 'သင်ဖန်တီးလိုသော စာသားအကြောင်းအရာကို ဖော်ပြပါ...',
    textPromptRequired: 'စာသား တောင်းဆိုမှု လိုအပ်ပါသည်',
    textPromptMinLength: 'တောင်းဆိုမှုသည် အနည်းဆုံး စာလုံး ၁၀ လုံး ရှိရမည်',
    contentLengthRequired: 'ကျေးဇူးပြု၍ အကြောင်းအရာ အရှည်ကို ရွေးချယ်ပါ',
    short: 'တို',
    medium: 'အလယ်အလတ်',
    long: 'ရှည်',
    toneRequired: 'ကျေးဇူးပြု၍ လေသံကို ရွေးချယ်ပါ',
    professional: 'ပရော်ဖက်ရှင်နယ်﻿',
    casual: 'ပေါ့ပေါ့ပါးပါး',
    friendly: 'ရင်းနှီးသော﻿',
    formal: 'Formal(တရားဝင်)',
    humorous: 'ဟာသဆန်သော',
    persuasive: 'ယုံကြည်လွယ်သော',
    targetAgeRequired: 'ကျေးဇူးပြု၍ ပစ်မှတ် အသက်အရွယ်ကို ရွေးချယ်ပါ',
    child: 'ကလေး (၅-၁၂)',
    teen: 'ဆယ်ကျော်သက် (၁၃-၁၇)',
    youngAdult: 'လူငယ် (၁၈-၂၅)',
    adult: 'လူကြီး (၂၆-၄၅)',
    senior: 'အသက်ကြီး (၄၅+)',
    allAges: 'အသက်အရွယ် အားလုံး',
    locationRequired: 'ကျေးဇူးပြု၍ တည်နေရာကို ရွေးချယ်ပါ',
    myanmar: 'မြန်မာ',
    global: 'ကမ္ဘာ့',
    contentPurposeRequired: 'ကျေးဇူးပြု၍ အကြောင်းအရာ ရည်ရွယ်ချက်ကို ရွေးချယ်ပါ',
    engagement: 'စိတ်ဝင်စားမှု',
    conversion: 'အရောင်းမြှင့်တင်ရန်',
    lead: 'ဝယ်ယူသူ ဆွဲဆောင်ရန်',
    increaseFollower: 'Follower မြှင့်တင်ရန်',
    emotionRequired: 'ကျေးဇူးပြု၍ စိတ်ခံစားမှုကို ရွေးချယ်ပါ',
    neutral: 'ပုံမှန်',
    happy: 'ပျော်ရွှင်',
    excited: 'စိတ်လှုပ်ရှားစရာ',
    calm: 'တည်ငြိမ်',
    serious: 'လေးလေးနက်နက်',
    inspiring: 'စိတ်အားထက်သန်စေသော',
    reference: 'ကိုးကား (ရွေးချယ်ချက်)',
    referencePlaceholder: 'ကိုးကား အချက်အလက်များကို ထည့်ပါ (ရွေးချယ်ချက်)...',
    generateContent: 'အကြောင်းအရာ ဖန်တီးမည်',
    generating: 'ဖန်တီးနေသည်...',
    
    // RecordVoiceModal
    recordAudioContent: 'အသံ အကြောင်းအရာ မှတ်တမ်းတင်မည်',
    startRecording: 'မှတ်တမ်းတင်မှု စတင်မည်',
    stopRecording: 'မှတ်တမ်းတင်မှု ရပ်မည်',
    pauseRecording: 'မှတ်တမ်းတင်မှု ခေတ္တရပ်မည်',
    resumeRecording: 'မှတ်တမ်းတင်မှု ပြန်စမည်',
    recordingTime: 'မှတ်တမ်းတင်သည့် အချိန်',
    audioPreview: 'အသံ ကြိုကြည့်ရှုမှု',
    reRecord: 'ပြန်လည်မှတ်တမ်းတင်မည်',
    uploadRecording: 'မှတ်တမ်းတင်ထားသည်ကို တင်မည်',
    voiceRecording: 'အသံ မှတ်တမ်းတင်မှု',
    recordingCompleted: 'မှတ်တမ်းတင်မှု ပြီးစီးပါပြီ',
    recordAgain: 'ပြန်လည်မှတ်တမ်းတင်မည်',
    recordingIndicator: 'မှတ်တမ်းတင်နေသည်...',
    recordAudioFirst: 'ကျေးဇူးပြု၍ ပထမဦးစွာ အသံမှတ်တမ်းတင်ပါ',
    
    // UploadImageModal
    uploadImageContent: 'ပုံ အကြောင်းအရာ တင်မည်',
    uploadImageFile: 'ပုံဖိုင် တင်မည်',
    chooseImageFile: 'ပုံဖိုင် ရွေးချယ်ပါ...',
    selectImageFile: 'ကျေးဇူးပြု၍ ပုံဖိုင်တစ်ခု ရွေးချယ်ပါ',
    selectImage: 'ပုံရွေးချယ်မည်',
    dragDropImage: 'ပုံကို ဤနေရာတွင် ဆွဲချပါ သို့မဟုတ် ရွေးချယ်ရန် နှိပ်ပါ',
    supportedFormats: 'ပံ့ပိုးသော ပုံစံများ: JPG, PNG, GIF',
    maxFileSize: 'အမြင့်ဆုံး ဖိုင်အရွယ်အစား: ၁၀MB',
    imagePreview: 'ပုံ ကြိုကြည့်ရှုမှု',
    changeImage: 'ပုံပြောင်းမည်',
    uploadImage: 'ပုံတင်မည်',
    
    // ContentDetailModal
    copyContent: 'အကြောင်းအရာ ကူးယူမည်',
    download: 'ဒေါင်းလုဒ်လုပ်မည်',
    recentContent: 'မကြာသေးမီ အကြောင်းအရာများ',
    
    // Alert messages
    imageUploadSuccess: 'ပုံတင်ခြင်း တောင်းဆိုမှု အောင်မြင်စွာ တင်သွင်းပြီးပါပြီ!',
    formSubmissionFailed: 'ဖောင် တင်သွင်းမှု မအောင်မြင်ပါ။ ကျေးဇူးပြု၍ ပြန်လည်ကြိုးစားပါ။',
    
    // Dashboard
    whatCreateToday: 'ဒီနေ့ ဘာကို ဖန်တီးချင်ပါသလဲ?',
    chooseOptions: 'ရှယ် content တစ်ပုဒ် ထုတ်ဖို့ အောက်က option ရွေးပါ',
    writeTextDescription: 'Content, ကြော်ငြာ, Announcement ကြိုက်ရာ ထုတ်ကြမယ်',
    uploadImageDescription: 'ပုံတင်ပြီး content ထုတ်မယ်',
    recordVoiceDescription: 'စကားပြောပြီး ကိုယ်လိုချင်တဲ့ content ကို ရေးခိုင်းပါ',
    
    // Login Page
    welcomeBack: 'ပြန်လည်ကြိုဆိုပါတယ်',
    signInToAccount: 'သင့်အကောင့်သို့ ဝင်ရောက်ပါ',
    emailAddress: 'အီးမေးလ်လိပ်စာ',
    enterEmail: 'သင့်အီးမေးလ်ကို ထည့်ပါ',
    emailRequired: 'အီးမေးလ် လိုအပ်ပါသည်',
    invalidEmail: 'မမှန်ကန်သော အီးမေးလ်လိပ်စာ',
    password: 'စကားဝှက်',
    enterPassword: 'သင့်စကားဝှက်ကို ထည့်ပါ',
    passwordRequired: 'စကားဝှက် လိုအပ်ပါသည်',
    passwordMinLength: 'စကားဝှက်သည် အနည်းဆုံး ၆ လုံး ရှိရမည်',
    rememberMe: 'ကျွန်ုပ်ကို မှတ်ထားပါ',
    signingIn: 'ဝင်ရောက်နေသည်...',
    signIn: 'ဝင်ရောက်မည်',
    dontHaveAccount: 'အကောင့်မရှိသေးပါလား?',
    signUpHere: 'ဤနေရာတွင် စာရင်းသွင်းပါ',
    loginFailed: 'အကောင့်ဝင်ခြင်း မအောင်မြင်ပါ။ ကျေးဇူးပြု၍ ပြန်လည်ကြိုးစားပါ။',
    
    // Register Page
    createAccount: 'အကောင့်ဖန်တီးမည်',
    joinUs: 'ကျွန်ုပ်တို့နှင့်အတူ ရှိရှိနေနေ အကြောင်းအရာများ ဖန်တီးပါ',
    fullNameRequired: 'အမည်အပြည့်အစုံ လိုအပ်ပါသည်',
    nameMinLength: 'အမည်သည် အနည်းဆုံး ၂ လုံး ရှိရမည်',
    enterFullName: 'သင့်အမည်အပြည့်အစုံကို ထည့်ပါ',
    chooseUsername: 'အသုံးပြုသူအမည် ရွေးချယ်ပါ',
    usernameRequired: 'အသုံးပြုသူအမည် လိုအပ်ပါသည်',
    usernameMinLength: 'အသုံးပြုသူအမည်သည် အနည်းဆုံး ၃ လုံး ရှိရမည်',
    usernamePattern: 'အသုံးပြုသူအမည်တွင် အက္ခရာ၊ ဂဏန်းနှင့် underscore သာ ပါဝင်နိုင်ပါသည်',
    enterEmailAddress: 'သင့်အီးမေးလ်လိပ်စာကို ထည့်ပါ',
    emailAddressRequired: 'အီးမေးလ်လိပ်စာ လိုအပ်ပါသည်',
    createPassword: 'စကားဝှက်ဖန်တီးပါ',
    passwordMinLength8: 'စကားဝှက်သည် အနည်းဆုံး ၈ လုံး ရှိရမည်',
    passwordPattern: 'စကားဝှက်တွင် အကြီးစာလုံး၊ အသေးစာလုံးနှင့် ဂဏန်း အနည်းဆုံး တစ်လုံးစီ ပါရှိရမည်',
    confirmPassword: 'စကားဝှက်အတည်ပြုမည်',
    confirmYourPassword: 'သင့်စကားဝှက်ကို အတည်ပြုပါ',
    pleaseConfirmPassword: 'ကျေးဇူးပြု၍ သင့်စကားဝှက်ကို အတည်ပြုပါ',
    passwordsNotMatch: 'စကားဝှက်များ မတူညီပါ',
    creatingAccount: 'အကောင့်ဖန်တီးနေသည်...',
    alreadyHaveAccount: 'အကောင့်ရှိပြီးသားလား?',
    signInHere: 'ဤနေရာတွင် ဝင်ရောက်ပါ',
    registrationFailed: 'စာရင်းသွင်းခြင်း မအောင်မြင်ပါ။ ကျေးဇူးပြု၍ ပြန်လည်ကြိုးစားပါ။',
    
    // Profile Page
    backToDashboard: 'မူလစာမျက်နှာသို့ ပြန်သွားမည်',
    profileSettings: 'ကိုယ်ရေးအကျဉ်း ဆက်တင်များ',
    changePhoto: 'ဓာတ်ပုံပြောင်းမည်',
    basicInformation: 'အခြေခံ အချက်အလက်များ',
    currentSubscription: 'လက်ရှိ စာရင်းသွင်းမှု',
    freePlan: 'အခမဲ့ အစီအစဉ်',
    proPlan: 'Pro အစီအစဉ်',
    premiumPlan: 'Premium အစီအစဉ်',
    active: 'လုပ်ဆောင်နေသည်',
    inactive: 'မလုပ်ဆောင်',
    nextBilling: 'နောက်ထပ် ငွေတောင်းခံမည့်ရက်',
    currentFeatures: 'လက်ရှိ အင်္ဂါရပ်များ',
    upgradeYourPlan: 'သင့်အစီအစဉ်ကို အဆင့်မြှင့်တင်ပါ',
    mostPopular: 'အရေပြားဆုံး',
    currentPlan: 'လက်ရှိ အစီအစဉ်',
    upgradeToPro: 'Pro သို့ အဆင့်မြှင့်တင်မည်',
    upgradeToPremiun: 'Premium သို့ အဆင့်မြှင့်တင်မည်',
    allPlansInclude: 'အစီအစဉ်အားလုံးတွင် ၁၄ ရက် အခမဲ့စမ်းသပ်ချိန် ပါဝင်ပါသည်။ မည်သည့်အချိန်မဆို ပယ်ဖျက်နိုင်ပါသည်။',
    changePassword: 'စကားဝှက်ပြောင်းမည်',
    currentPassword: 'လက်ရှိ စကားဝှက်',
    currentPasswordRequired: 'လက်ရှိ စကားဝှက် လိုအပ်ပါသည်',
    newPassword: 'စကားဝှက်အသစ်',
    newPasswordRequired: 'စကားဝှက်အသစ် လိုအပ်ပါသည်',
    passwordMustContain: 'စကားဝှက်တွင် အကြီးစာလုံး၊ အသေးစာလုံးနှင့် ဂဏန်း ပါရှိရမည်',
    confirmNewPassword: 'စကားဝှက်အသစ် အတည်ပြုမည်',
    pleaseConfirmNewPassword: 'ကျေးဇူးပြု၍ သင့်စကားဝှက်အသစ်ကို အတည်ပြုပါ',
    saveChanges: 'ပြောင်းလဲမှုများ သိမ်းဆည်းမည်',
    profileUpdatedSuccess: 'ကိုယ်ရေးအကျဉ်း ပြင်ဆင်မှု အောင်မြင်ပါပြီ!',
    profileUpdateFailed: 'ကိုယ်ရေးအကျဉ်း ပြင်ဆင်မှု မအောင်မြင်ပါ။ ကျေးဇူးပြု၍ ပြန်လည်ကြိုးစားပါ။',
    redirectingCheckout: '{plan} အစီအစဉ် ငွေချေမှု စာမျက်နှာသို့ ပို့နေသည်...',
    
    // Subscription Features
    feature1: 'တစ်လလျှင် AI ဖန်တီးထားသော အကြောင်းအရာ ၅ ခု',
    feature2: 'အခြေခံ ပုံစံများ',
    feature3: 'ပုံမှန် ပံ့ပိုးမှု',
    feature4: 'အကန့်အသတ်မရှိ AI ဖန်တီးထားသော အကြောင်းအရာ',
    feature5: 'အဆင့်မြင့် ပုံစံများ',
    feature6: 'ဦးစားပေး ပံ့ပိုးမှု',
    feature7: 'ကိုယ်ပိုင် အမှတ်တံဆိပ်',
    feature8: 'ခွဲခြမ်းစိတ်ဖြာမှု ဒက်ရှ်ဘုတ်',
    feature9: 'Pro တွင်ပါသော အရာအားလုံး',
    feature10: 'AI အသံဖန်တီးမှု',
    feature11: 'အဆင့်မြင့် ပုံပြင်ဆင်မှု',
    feature12: 'အဖွဲ့လုပ်ဆောင်မှု',
    feature13: 'API အသုံးပြုခွင့်',
    feature14: 'White-label ဖြေရှင်းချက်များ',
    
    // Business Information Form
    businessInformation: 'လုပ်ငန်း အချက်အလက်များ',
    businessInformationDescription: 'သင့်အတွက် ပိုမိုကောင်းမွန်သော အကြောင်းအရာများ ဖန်တီးနိုင်ရန် သင့်လုပ်ငန်းအကြောင်း ပြောပြပါ',
    businessName: 'လုပ်ငန်းအမည်',
    businessNamePlaceholder: 'ဥပမာ - "The Daily Grind Cafe"',
    businessNameRequired: 'လုပ်ငန်းအမည် လိုအပ်ပါသည်',
    businessNameMinLength: 'လုပ်ငန်းအမည်သည် အနည်းဆုံး ၂ လုံး ရှိရမည်',
    businessNameMaxLength: 'လုပ်ငန်းအမည်သည် ၁၀၀ လုံးထက် မပိုရပါ',
    coreOffering: 'အဓိက ပေးဆောင်မှု/နယ်ပယ်',
    coreOfferingPlaceholder: 'ဥပမာ - "လက်မှုပညာ ကော်ဖီနှင့် အိမ်လုပ် မုန့်များ"',
    coreOfferingRequired: 'အဓိက ပေးဆောင်မှု လိုအပ်ပါသည်',
    coreOfferingMinLength: 'အဓိက ပေးဆောင်မှုသည် အနည်းဆုံး ၅ လုံး ရှိရမည်',
    coreOfferingMaxLength: 'အဓိက ပေးဆောင်မှုသည် ၂၀၀ လုံးထက် မပိုရပါ',
    uniqueSellingProposition: 'ထူးခြားသော ရောင်းချမှု အဆိုပြုချက်',
    uniqueSellingPropositionPlaceholder: 'ဥပမာ - "ကျွန်ုပ်တို့သည် အော်ဂဲနစ်၊ ကျင့်ဝတ်နှင့်အညီ ရယူထားသော ကော်ဖီစေ့များကိုသာ အသုံးပြုပြီး အမြတ်ငွေ ၁၀% ကို ဒေသတွင်း အိုးမဲ့အိမ်မဲ့များအတွက် လှူဒါန်းပါသည်။"',
    uniqueSellingPropositionRequired: 'ထူးခြားသော ရောင်းချမှု အဆိုပြုချက် လိုအပ်ပါသည်',
    uniqueSellingPropositionMinLength: 'USP သည် အနည်းဆုံး ၁၀ လုံး ရှိရမည်',
    uniqueSellingPropositionMaxLength: 'USP သည် ၅၀၀ လုံးထက် မပိုရပါ',
    targetAudience: 'ပစ်မှတ် ပရိသတ်',
    targetAudiencePlaceholder: 'ဥပမာ - "မြို့လယ်ပိုင်းရှိ အဝေးမှလုပ်သူများနှင့် မိသားစုများ"',
    targetAudienceRequired: 'ပစ်မှတ် ပရိသတ် လိုအပ်ပါသည်',
    targetAudienceMinLength: 'ပစ်မှတ် ပရိသတ်သည် အနည်းဆုံး ၅ လုံး ရှိရမည်',
    targetAudienceMaxLength: 'ပစ်မှတ် ပရိသတ်သည် ၂၀၀ လုံးထက် မပိုရပါ',
    businessMission: 'သင့်လုပ်ငန်း၏ အဓိက ရည်မှန်းချက် သို့မဟုတ် တန်ဖိုးက ဘာလဲ?',
    businessMissionPlaceholder: 'ဥပမာ - "ဒေသတွင်း အသိုက်အဝန်းများနှင့် သဘာဝပတ်ဝန်းကျင် ထိန်းသိမ်းရေးကို ပံ့ပိုးပေးရင်း ရေရှည်တည်တံ့နိုင်သော အရည်အသွေးမြင့် ကုန်ပစ္စည်းများ ပေးဆောင်ရန်။"',
    businessMissionRequired: 'လုပ်ငန်း ရည်မှန်းချက် သို့မဟုတ် တန်ဖိုး လိုအပ်ပါသည်',
    businessMissionMinLength: 'လုပ်ငန်း ရည်မှန်းချက်သည် အနည်းဆုံး ၁၀ လုံး ရှိရမည်',
    businessMissionMaxLength: 'လုပ်ငန်း ရည်မှန်းချက်သည် ၅၀၀ လုံးထက် မပိုရပါ',
    saveBusinessInfo: 'လုပ်ငန်း အချက်အလက်များ သိမ်းဆည်းမည်',
    
    // Initial Business Setup
    setupFirstBusiness: 'သင့်ပထမ လုပ်ငန်း ထည့်သွင်းပါ',
    businessSetupRequired: 'ကျေးဇူးပြု၍ အကြောင်းအရာ ဖန်တီးခြင်းမတိုင်မီ လုပ်ငန်းတစ်ခု အနည်းဆုံး ထည့်သွင်းပါ',
    addFirstBusinessDescription: 'အကြောင်းအရာ ဖန်တီးခြင်း စတင်ရန်အတွက် သင့်လုပ်ငန်း အချက်အလက်များကို ရှေးဦးစွာ ထည့်သွင်းရန် လိုအပ်ပါသည်။ ၎င်းသည် သင့်အမှတ်တံဆိပ်အတွက် ပိုမို သက်ဆိုင်ပြီး ပစ်မှတ်ထားသော အကြောင်းအရာများ ဖန်တီးရာတွင် ကူညီပေးပါသည်။'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'my';
  });

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const value = {
    language,
    changeLanguage,
    t,
    isMyanmar: language === 'my'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;